#- alias: 'track sensor state of Jay Room Locator'
#  trigger:
#    platform: mqtt
#    topic: owntracks/jays7/galaxy s7/event
#  condition:
#    condition: or
#    conditions:
#    - condition: template
#      value_template: "{{ trigger.payload_json['desc'] == '-den' }}"
#    - condition: template
#      value_template: "{{ trigger.payload_json['desc'] == '-master bedroom' }}"
#    - condition: template
#      value_template: "{{ trigger.payload_json['desc'] == '-basement' }}"
#  action:
#    service_template: "input_boolean.turn_{{ 'on' if trigger.payload_json['event'] == 'enter' else 'off' }}"
#    data_template:
#      entity_id: "input_boolean.jay_phone_{{ 'den' if trigger.payload_json['desc'] == '-den' else 'master' if trigger.payload_json['desc'] == '-master bedroom' else 'basement' }}"
- alias: 'track sensor state of Jay WiFi Locator'
  trigger:
    - platform: state
      entity_id: sensor.jay_wifi_locator
#    - platform: state
#      entity_id: sensor.jay_wifi_locator_1
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: "input_boolean.jay_phone{{ '_den' if trigger.from_state.state == 'den' else '_master' if trigger.from_state.state == 'master bedroom' else '_basement' if trigger.from_state.state == 'basement'
                    else '_kitchen' if trigger.from_state.state == 'kitchen' else '_lr' if trigger.from_state.state == 'livingroom' else '_gym' if trigger.from_state.state == 'gym' }}"
    - service: input_boolean.turn_on
      data_template:
        entity_id: "input_boolean.jay_phone{{ '_den' if trigger.to_state.state == 'den' else '_master' if trigger.to_state.state == 'master bedroom' else '_basement' if trigger.to_state.state == 'basement'
                    else '_kitchen' if trigger.to_state.state == 'kitchen' else '_lr' if trigger.to_state.state == 'livingroom' else '_gym' if trigger.to_state.state == 'gym' }}"
    - service: input_select.select_option
      data_template:
        entity_id: input_select.jay_room_tracker
        option: "{{ 'den' if trigger.to_state.state == 'den' else 'master' if trigger.to_state.state == 'master bedroom' else 'basement' if trigger.to_state.state == 'basement'
                else 'kitchen' if trigger.to_state.state == 'kitchen' else 'livingroom' if trigger.to_state.state == 'livingroom' else 'gym' if trigger.to_state.state == 'gym' }}"
#    - service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.jay_home
#    - service: tts.google_say
#      entity_id: media_player.living_room
#      data_template:
#        message: "Jay moved rooms to {{ trigger.to_state.state ~ ' ' ~ trigger.for ~ ' seconds ago' }}"

- alias: 'Lily Away'
#  initial_state: True
  condition:
    condition: state
    entity_id: input_boolean.lily_home
    state: 'on'
  trigger:
    platform: state
    entity_id: group.lily
    to: 'not_home'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.lily_home

- alias: 'Lily Home'
#  initial_state: False
  condition:
    condition: state
    entity_id: input_boolean.lily_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.lilygarrsiphone
      to: 'home'
    - platform: state
      entity_id: device_tracker.lilysapplewatch
      to: 'home'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.lily_home

- alias: 'Madeline Away'
#  initial_state: False
  condition:
    condition: state
    entity_id: input_boolean.maddie_home
    state: 'on'
  trigger:
    platform: state
    entity_id: group.madeline
    to: 'not_home'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.maddie_home

- alias: 'Madeline Home'
#  initial_state: True
  condition:
    condition: state
    entity_id: input_boolean.maddie_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.6c4d73193aab
      to: 'home'
    - platform: state
      entity_id: device_tracker.d88f76cb2ae7
      to: 'home'
    - platform: state
      entity_id: device_tracker.madelinplewatch
      to: 'home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.maddie_home

- alias: 'Jay Home'
#  initial_state: True
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.jay_home
        state: 'off'
      - condition: numeric_state
        entity_id: group.jay
        above: '1'
        value_template: "{{ dict(( states|selectattr('entity_id', 'in', state_attr('group.jay', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  trigger:
    - platform: state
      entity_id:
        - device_tracker.jay_galaxys9
        - device_tracker.tile_bbcc7226a36f4551
        - device_tracker.tile_p_6592b29a51b689a4f4217c1f4100d865
      to: 'home'
  action:
     service: input_boolean.turn_on
     entity_id: input_boolean.jay_home

- alias: 'Jay Not Home'
#  initial_state: False
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.jay_home
        state: 'on'
      - condition: numeric_state
        entity_id: group.jay
        below: '2'
        value_template: "{{ dict(( states|selectattr('entity_id', 'in', state_attr('group.jay', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  trigger:
    - platform: state
      entity_id:
        - device_tracker.jay_galaxys9
        - device_tracker.tile_bbcc7226a36f4551
        - device_tracker.tile_p_6592b29a51b689a4f4217c1f4100d865
      to: 'not_home'
      for:
        minutes: '1'
  action:
     service: input_boolean.turn_off
     entity_id: input_boolean.jay_home
